version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./.docker/conf/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
      - db

  php:
    build: .docker
    restart: always
    volumes:
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:latest
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_HOST=${DB_HOST}
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_PORT=${DB_PORT}
    ports:
      - 5432:5432
